# Generated by Django 4.1.13 on 2024-05-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_picture", "0012_alter_picture_cmsplugin_ptr"),
        ("djangocms_picture", "0012_auto_20220504_2117"),
    ]

    operations = []
